# This file is managed by rcm, all manual changes will be lost
# zsh version: 5.8.1
# antigen version: 2.2.2

export TERM="xterm-256color"
export EDITOR="vim"

HIST_STAMPS="yyyy-mm-dd"
UPDATE_ZSH_DAYS="30"
COMPLETION_WAITING_DOTS="true"

# ADOTDIR="$HOME/.antigen"

ANTIGEN_BUNDLES="$HOME/.antigen/bundles"
ANTIGEN_PLUGIN_UPDATE_DAYS="30"
ANTIGEN_SYSTEM_UPDATE_DAYS="30"


source "$HOME/.antigen/antigen/antigen.zsh"

antigen use oh-my-zsh


# antigen bundle lukechilds/zsh-nvm
antigen bundle command-not-found
antigen bundle docker
antigen bundle docker-compose
antigen bundle fancy-ctrl-z
antigen bundle git-extras
antigen bundle gnu-utils
antigen bundle systemd
antigen bundle python
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle popstas/zsh-command-time
antigen bundle unixorn/autoupdate-antigen.zshplugin
antigen bundle andrewferrier/fzf-z
antigen bundle ytet5uy4/fzf-widgets
# will fixed in zsh-autosuggestion v0.4 - https://github.com/zsh-users/zsh-autosuggestions/pull/218
if (( ZSHRC_LOAD_ONCE++ == 0 )); then
    antigen bundle zdharma/fast-syntax-highlighting@v1.2
fi

POWERLEVEL9K_INSTALLATION_PATH=$ANTIGEN_BUNDLES/bhilburn/powerlevel9k/powerlevel9k.zsh-theme

antigen theme romkatv/powerlevel10k powerlevel10k

antigen apply

###

unsetopt share_history


autoload -Uz copy-earlier-word
zle -N copy-earlier-word

# hotkeys
bindkey '\e[1~' beginning-of-line
bindkey '\e[4~' end-of-line
bindkey '^@' fzf-select-widget
bindkey '^@.' fzf-edit-dotfiles
bindkey '^@c' fzf-change-directory
bindkey '^@f' fzf-edit-files
bindkey '^@k' fzf-kill-processes
bindkey '^@s' fzf-exec-ssh
bindkey '^\' fzf-change-recent-directory
bindkey '^r' fzf-insert-history
bindkey '^xf' fzf-insert-files
bindkey '^xd' fzf-insert-directory
bindkey '^@g' fzf-select-git-widget
bindkey '^@ga' fzf-git-add-files
bindkey '^@gc' fzf-git-change-repository
bindkey '^@gco' fzf-git-checkout-branch
bindkey '^@gd' fzf-git-delete-branches
bindkey '^@gh' fzf-select-github-widget
bindkey '^@ghi' fzf-github-show-issue
bindkey '^@ghe' fzf-github-edit-issue
bindkey '^@gho' fzf-github-open-issue
bindkey '^@ghc' fzf-github-close-issue
bindkey '^@ghco' fzf-github-comment-issue
bindkey '^@d' fzf-select-docker-widget
bindkey '^@dk' fzf-docker-kill-containers
bindkey '^@dl' fzf-docker-logs-container
bindkey '^@dr' fzf-docker-remove-containers
bindkey '^@dri' fzf-docker-remove-images
bindkey '^@drv' fzf-docker-remove-volumes
bindkey '^@dsa' fzf-docker-start-containers
bindkey '^@dso' fzf-docker-stop-containers
bindkey '^U' autosuggest-accept

# aliases
alias 'reset'="tput reset" # faster reset
alias 'eo'="exo-open" # open files with system editor
alias 'xo'='xdg-open' # open files with system editor
alias 'iotop'="sudo iotop -aPo"  # show processes writing to disk
alias 'dlb'='git branch --merged | grep -Ev "(^\*|master|main|dev|develop)" | xargs git branch -d' # delete local branches
alias ff='rg --files --hidden --no-ignore | rg -S' # find files with rg
alias rgi='rg -i' # insensitive rg
alias wifi_stats='watch -n1 $HOME/.dotfiles/unlinked/wifi_stats.sh' # show details for wifi connection

# find in pdfs
alias rgapdf='rga --rga-adapters=poppler'

# exit like in vim
alias :q='exit'

# fzf
export FZF_TMUX=0
export FZF_DEFAULT_OPTS="--height 100% --reverse"

# in case https://github.com/Qix-/better-exceptions is instal/led
export BETTER_EXCEPTIONS=1

# fzf-widgets: fzf-change-reset-dir
autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
add-zsh-hook chpwd chpwd_recent_dirs
declare -p FZF_WIDGETS_OPTS > /dev/null 2>&1 && FZF_WIDGETS_OPTS[insert-history]="--exact"
declare -p FZF_WIDGET_OPTS > /dev/null 2>&1 && FZF_WIDGET_OPTS[insert-history]="--exact"

# zsh-autosuggestions
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=15
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=240" # gray highlight

# powerlevel9k
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_STATUS_VERBOSE=true
POWERLEVEL9K_STATUS_CROSS=false
POWERLEVEL9K_STATUS_OK=false


POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir virtualenv)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs vcs command_execution_time time)
DEFAULT_USER=$USER
POWERLEVEL9K_ALWAYS_SHOW_CONTEXT=true
POWERLEVEL9K_ALWAYS_SHOW_USER=false

POWERLEVEL9K_CUSTOM_COMMAND_TIME="zsh_command_time"
POWERLEVEL9K_CUSTOM_COMMAND_TIME_BACKGROUND="248"
POWERLEVEL9K_CUSTOM_COMMAND_TIME_FOREGROUND="000"

# https://github.com/bhilburn/powerlevel9k#command_execution_time
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD="3"

POWERLEVEL9K_PROMPT_ON_NEWLINE=false
POWERLEVEL9K_RPROMPT_ON_NEWLINE=false
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="255"
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND="024"
POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND="255"
POWERLEVEL9K_CONTEXT_REMOTE_BACKGROUND="024"
POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND="255"
POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND="124"

POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="255"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="240"
POWERLEVEL9K_DIR_HOME_FOREGROUND="255"
POWERLEVEL9K_DIR_HOME_BACKGROUND="240"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="255"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="240"

POWERLEVEL9K_VCS_CLEAN_BACKGROUND="100"
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="094"
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="094"
POWERLEVEL9K_VCS_CLEAN_FOREGROUND="232"
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="232"
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="232"

POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND="000"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND="248"

# aliases
alias suser='su -'

# integrate direnv
eval "$(direnv hook zsh)"

# update path
# must be at the end to make oh-my-zsh AUTO_CD work properly, see
# https://unix.stackexchange.com/questions/325846/ohmyzsh-opens-folder-instead-of-command-autocd
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"

# disable CTRL+s shortcut to stale the terminal (not a usecase)
stty -ixon

# user configs
zshrc_conf_glob="/etc/zsh/zshrc.local"
zshrc_conf_home="$HOME/.zshrc.local"
if test -r $zshrc_conf_glob -a -f $zshrc_conf_glob;then source $zshrc_conf_glob; fi
if test -r $zshrc_conf_home -a -f $zshrc_conf_home;then source $zshrc_conf_home; fi
