[[manager.prepend_keymap]]
on   = "T"
run  = 'shell --detach kitty --working-directory $PWD'
desc = "Open shell here"

[[manager.prepend_keymap]]
desc = "Start bunny.yazi"
on = "b"
run = "plugin bunny"
