[manager]
sort_by = "natural"

[opener]
play = [
    { run = 'mpv "$@"', orphan = true, for = "unix" },
]
# edit = [
#     { run = 'shell --detach \"kitty -e lvim "$@"\"', block = true, for = "unix" },
# ]
open = [
    { run = 'xdg-open "$@"', desc = "Open" },
    { run = 'code "$@"', desc = "VS Code" },
]
