#!/bin/sh

# activate only laptop

if hostname | grep "tux05"; then
	# special handling of Lenovo E420s
	# LVDS1 laptop
	xrandr --output HDMI1 --off --output LVDS1 --mode 1366x768
else
	# Tuxedo
	# eDP1 laptop
	# DP1 display port
	xrandr --output eDP1 --mode 1920x1080 --output DP1 --off --output HDMI2 --off
fi

# Load panel config
xfce4-panel-profiles load ~/.dotfiles/unlinked/panel-config/lap.tar.bz2

# Arrange desktop icons
xfdesktop -A

