#!/bin/sh

# need to run that after suspend/standby to get Thunderbolt dock working
lspci

# activate all monitors
# eDP1 laptop
# DP1 middle monitor
# HDMI2 right monitor
xrandr --output eDP-1 --mode 1920x1080 --pos 0x977 --output DP-1 --mode 2560x1440 --primary --pos 1920x0 --output HDMI-1 --mode 2560x1440 --pos 4480x0

# Load panel config
xfce4-panel-profiles load ~/.dotfiles/unlinked/panel-config/dock.tar.bz2

# Arrange desktop icons
xfdesktop -A

# Wait a while until dock sound device is ready
sleep 10s

# Set default audio sink to the dock station
sh ~/.dotfiles/unlinked/set_audio_dock.sh

