#!/bin/sh

hostname=$(hostnamectl hostname)

# activate laptop + right wqhd monitor
if [ "$hostname" = "tux09" ]; then
  # Tuxedo InfinityBook Pro 16 Gen 7
  xrandr --output eDP-1 --mode 2560x1600 --pos 2560x810 --output DP-1 --off --output HDMI-1 --off --output DP-3 --mode 2560x1440 --pos 0x0 --primary
  # Load panel config
  ~/.dotfiles/unlinked/panel-config/set_panels.sh -c2
else
  echo "Hostname ${hostname} unknown"
  exit 1
fi
set_panels.sh
# connect to SC-PM250
bluetoothctl connect 80:C7:55:3B:9E:B4

# Arrange desktop icons
xfdesktop -A
