#!/bin/sh

hostname=$(hostnamectl hostname)

# activate laptop + right wqhd monitor
if [ "$hostname" = "tux09" ]; then
  # Tuxedo InfinityBook Pro 16 Gen 7
  xrandr --output eDP-1 --mode 2560x1600 --pos 0x1094 --output DP-1 --off --output HDMI-1 --off --output DP-3 --mode 2560x1440 --pos 2560x0 --primary
  # Load panel config
  ~/.dotfiles/unlinked/panel-config/set_panels.sh -c2
  xfconf-query -c xfce4-panel --create --type string -p /panels/panel-0/output-name -s Primary
  xfconf-query -c xfce4-panel --create --type string -p /panels/panel-1/output-name -s Automatic
else
  echo "Hostname ${hostname} unknown"
  exit 1
fi

# connect to SC-PM250
bluetoothctl connect 80:C7:55:3B:9E:B4

# Arrange desktop icons
xfdesktop -A
