#!/bin/sh

# activate laptop + right wqhd monitor
if hostname | grep "tux07"; then
  # # Tuxedo InifinityBook S15 Gen 6
  xfconf-query --create -c displays -p "/Schemes/Apply" -t string -s "35abb09819106a210cbbfd5dd98f522f9c492991"
  # Load panel config
  xfce4-panel-profiles load ~/.dotfiles/unlinked/panel-config/hdmi_r_tux07.tar.bz2
elif hostname | grep "tux01"; then
  # Tuxedo InfinityBook Pro v4
  xrandr --output eDP-1 --mode 1920x1080 --pos 0x980 --output DP-1 --off --output HDMI-2 --mode 2560x1440 --pos 1920x0 --primary
  # Load panel config
  xfce4-panel-profiles load ~/.dotfiles/unlinked/panel-config/hdmi_r_tux01.tar.bz2
else
  echo "Hostname ${hostname} unknown"
  exit 1
fi

# Arrange desktop icons
xfdesktop -A

